name: Setup Windows Dependencies
description: Setup Windows Build Dependencies
runs:
  using: "composite"
  steps:

    - name: Install CMake (Windows)
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.28'

    - name: Install Ninja (Windows)
      shell: powershell
      run: |
        choco install ninja
        choco install ccache
        choco upgrade ccache ninja

    # This forces the use of MSVC rather than GCC
    - uses: ilammy/msvc-dev-cmd@v1.12.1
